DROP TABLE IF EXISTS given;
CREATE TABLE given (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  lastaudit DATE NOT NULL,person VARCHAR(100) NOT NULL ,
  PRIMARY KEY (id));

DROP TABLE IF EXISTS product;
CREATE TABLE product(
  id  INT NOT NULL, productname VARCHAR(100) NOT NULL ,
  PRIMARY KEY (id));